import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from data_generator import generate_hcp_data
from hcp_segmentation import perform_segmentation
from churn_prediction import train_churn_model
from nba_recommender import apply_nba

# Page configuration
st.set_page_config(page_title="AI-Powered Pharma CRM", layout="wide")

st.title("🏥 AI-Powered CRM Enhancement for Pharma SFE")
st.markdown("""
이 대시보드는 제약사 CRM 데이터에 AI/ML을 적용하여 **HCP 세분화, 이탈 위험 예측, Next Best Action(NBA)**을 제공합니다.
""")

# Sidebar for controls
st.sidebar.header("Pipeline Controls")
n_hcps = st.sidebar.slider("Number of HCPs to simulate", 100, 2000, 500)
run_btn = st.sidebar.button("Run Full AI Pipeline")

# Initialize session state for data
if 'df' not in st.session_state:
    st.session_state.df = None

if run_btn:
    with st.spinner("Running AI Pipeline..."):
        # Step 0: Data Generation
        df = generate_hcp_data(n_hcps=n_hcps)
        # Step 1: Segmentation
        df, _, _ = perform_segmentation(df, n_clusters=4)
        # Step 2: Churn Prediction
        df, _, _ = train_churn_model(df)
        # Step 3: NBA
        df = apply_nba(df)
        st.session_state.df = df
        st.success("✅ Pipeline Execution Complete!")

if st.session_state.df is not None:
    df = st.session_state.df

    # --- KPI Overview ---
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total HCPs", len(df))
    col2.metric("High Risk HCPs", len(df[df['churn_risk_level'] == '🔴 High Risk']))
    col3.metric("Avg Churn Risk", f"{df['churn_risk_score'].mean():.1%}")
    col4.metric("Top Segment", df['segment_name'].value_counts().index[0])

    # --- Visualizations ---
    st.divider()
    vcol1, vcol2 = st.columns(2)

    with vcol1:
        st.subheader("HCP Segmentation & Churn Rate")
        seg_data = df.groupby('segment_name').agg({'hcp_id': 'count', 'churn': 'mean'}).round(3)
        fig1, ax1 = plt.subplots(figsize=(10, 6))
        seg_data['hcp_id'].plot(kind='bar', ax=ax1, color='skyblue')
        ax1.set_ylabel("HCP Count")
        ax1.tick_params(axis='x', rotation=45)
        st.pyplot(fig1)

    with vcol2:
        st.subheader("Churn Risk Levels")
        risk_counts = df['churn_risk_level'].value_counts()
        fig2, ax2 = plt.subplots(figsize=(8, 8))
        ax2.pie(risk_counts, labels=risk_counts.index, autopct='%1.1f%%', 
                colors=['#2ecc71', '#f1c40f', '#e74c3c'], startangle=90)
        st.pyplot(fig2)

    # --- Data Explorer ---
    st.divider()
    st.subheader("🔍 HCP Insights & NBA Recommendations")
    
    search_q = st.text_input("Search HCP by ID or Specialty", "")
    filtered_df = df
    if search_q:
        filtered_df = df[df['hcp_id'].str.contains(search_q, case=False) | 
                         df['specialty'].str.contains(search_q, case=False)]

    st.dataframe(filtered_df[[
        'hcp_id', 'specialty', 'segment_name', 'churn_risk_level', 
        'priority_score', 'nba_channel', 'nba_content', 'nba_frequency'
    ]].sort_values('priority_score', ascending=False), use_container_width=True)

    # Download link
    csv = df.to_csv(index=False, encoding='utf-8-sig').encode('utf-8-sig')
    st.download_button(
        "Download Full Results (CSV)",
        csv,
        "pharma_ai_crm_results.csv",
        "text/csv",
        key='download-csv'
    )

else:
    st.info("👈 왼쪽 사이드바의 'Run Full AI Pipeline' 버튼을 눌러 시뮬레이션을 시작하세요.")

st.sidebar.divider()
st.sidebar.info(f"Generated by Antigravity | {pd.Timestamp.now().strftime('%Y-%m-%d')}")
